<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pdl</string>
	</array>
	<key>name</key>
	<string>pdlex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolate</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>^(%(?:alias|var\[\]|var))\ +(\$?\w+)(.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(%include)\ +(?:(nil)|(".*"))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(%a?context) (.*)(#.*)?\n</string>
			<key>name</key>
			<string>markup.heading.3.pdlex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?![\n\r%])</string>
			<key>end</key>
			<string>\s</string>
			<key>name</key>
			<string>string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolate</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\u[a-fA-F0-9]+|\\x[a-fA-F0-9]{2}|\\p\{.+?\}|\\.</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>interpolate</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\{).+?(\})</string>
			<key>name</key>
			<string>variable</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pdlex</string>
	<key>uuid</key>
	<string>612AA9FB-3247-432A-BFC5-CD568A96F53D</string>
</dict>
</plist>
